/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:235c3c8b-5ad4-4b0d-ae01-e7586c4646c2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vLQR5hIkm",
    "aws_user_pools_web_client_id": "4209pa1liugjbv9u5ss1lubo7p",
    "oauth": {}
};


export default awsmobile;
